class Exception1
{
	public static void main (String ar[])
	{
	   try
	   {
		 System.out.println(10/0);
		 	   }
	   catch(Exception e)
	   {
		   System.out.println("Exception Handled");
	   }
	}
}